version: '3.8'

services:
  # PostgreSQL for metadata storage
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mediaindex
      POSTGRES_PASSWORD: mediaindex123
      POSTGRES_DB: mediaindex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medianet

  # Qdrant vector database for semantic search
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - medianet

  # MinIO for S3-compatible object storage
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - medianet

  # Redis for caching and job queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - medianet

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mediaindex:mediaindex123@postgres:5432/mediaindex_db
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-change-this
    depends_on:
      - postgres
      - qdrant
      - minio
      - redis
    volumes:
      - ./backend:/app
    networks:
      - medianet

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - medianet

  # Celery worker for background tasks
  celery-worker:
    build: ./backend
    command: celery -A core.celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://mediaindex:mediaindex123@postgres:5432/mediaindex_db
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - qdrant
      - minio
      - redis
    volumes:
      - ./backend:/app
    networks:
      - medianet

volumes:
  postgres_data:
  qdrant_data:
  minio_data:

networks:
  medianet:
    driver: bridge 